In [1]:
import numpy as np

In [25]:

x1 = np.random.randint(0, 10, size=10)
x2 = np.random.randint(0, 10, size=10)
x = np.stack([x1, x2], axis=1)
Y = np.random.randint(0, 10, size=(10, 1))


print(x1)
print(x2)
print(x)

print(Y)
print(Y.shape)

[7 5 4 7 9 5 9 6 9 4]
[6 1 6 4 9 6 3 8 4 3]
[[7 6]
 [5 1]
 [4 6]
 [7 4]
 [9 9]
 [5 6]
 [9 3]
 [6 8]
 [9 4]
 [4 3]]
[[7]
 [2]
 [7]
 [3]
 [1]
 [5]
 [4]
 [2]
 [7]
 [3]]
(10, 1)


In [38]:
w1 = np.random.rand(3)
w2 = np.random.rand(3)
w = np.stack([w1, w2], axis=0)
b = np.random.rand(3)
b

array([0.74983689, 0.26053554, 0.10485097])

In [ ]:
x1 = np.random.randint(0, 10, size=10)
x2 = np.random.randint(0, 10, size=10)
x = np.stack([x1, x2], axis=1)
Y = np.random.randint(0, 10, size=(10, 1))

w1 = np.random.rand(3)
w2 = np.random.rand(3)
w_h1 = np.stack([w1, w2], axis=0)
b_h1 = np.random.rand(3)

w1 = np.random.rand(3)
w2 = np.random.rand(3)
w3 = np.random.rand(3)
w_h2 = np.stack([w1, w2, w3], axis=0)
b_h2 = np.random.rand(3)

w1 = np.random.rand(1)
w2 = np.random.rand(1)
w3 = np.random.rand(1)
w_o = np.stack([w1, w2, w3], axis=0)
b_0 = np.random.rand(1)

In [ ]:


def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def layer(x, w, b):
    z = (x @ w) + b
    a = sigmoid(z)
    return a

x = layer(x, w_h1, b_h1)
x = layer(x, w_h2, b_h2)
output = layer(x, w_0, b_0)

output.shape