In [1]:
import numpy as np

# Identity

In [2]:
def identity(x):
    return x

def identity_grad(x):
    return np.ones_like(x)

In [3]:
x = np.array([1, 4, 7, 8])
x = identity(x)
identity_grad(x)

array([1, 1, 1, 1])

# Binary Step

In [4]:
def binaryStep(x):
    return np.where(x > 0, 1.0, 0.0)

def binaryStep_grad(x):
    grad = np.zeros_like(x, dtype=float)
    grad[x == 0] = np.nan
    return grad

In [5]:
x = np.array([-1, 4, 0, 8])
x = binaryStep(x)
print(x)
print(binaryStep_grad(x))

[0. 1. 0. 1.]
[nan  0. nan  0.]


# Sigmoid

In [6]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def sigmoid_grad(x):
    fx = sigmoid(x)
    return fx - (1 - fx)

In [7]:
x = np.array([1, 4, 7, 8])
x = sigmoid(x)
print(x)
print(sigmoid_grad(x))

[0.73105858 0.98201379 0.99908895 0.99966465]
[0.35007505 0.45501523 0.46175883 0.46198528]


# TanH

In [8]:
def tanh(x):
    return np.tanh(x)
def tanh2(x):
    tan = (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))
    return tan

def tanh_grad(x):
    return 1 - np.tanh(x) ** 2

In [9]:
x = np.array([1, 4, 7, 8])
x = tanh(x)
print(x)
print(tanh_grad(x))

[0.76159416 0.9993293  0.99999834 0.99999977]
[0.58781675 0.42040353 0.41997541 0.41997449]


In [10]:
x = np.array([1, 4, 7, 8])
x = tanh2(x)
print(x)
print(tanh_grad(x))

[0.76159416 0.9993293  0.99999834 0.99999977]
[0.58781675 0.42040353 0.41997541 0.41997449]


# ArchTan

In [11]:
def archtan(x):
    return np.arctan(x)
def archtan_grad(x):
    return 1 / (1 + x ** 2)

In [12]:
x = np.array([1, 4, 7, 8])
x = archtan(x)
print(x)
print(archtan_grad(x))

[0.78539816 1.32581766 1.42889927 1.44644133]
[0.61848646 0.36260886 0.32875778 0.32339513]


# Relu

In [13]:
def relu(x):
    return np.maximum(0, x)
def relu_grad(x):
    return np.where(x > 0, 1.0, 0.0)

In [14]:
x = np.array([1, 4, -3, 8])
x = relu(x)
print(x)
print(relu_grad(x))

[1 4 0 8]
[1. 1. 0. 1.]


# Prelu

In [15]:
def prelu(x, alpha = 0.01):
    return np.where(x > 0, x, alpha * x)
def prelu_grad(x, alpha = 0.01):
    return np.where(x > 0, 1, alpha)

In [16]:
x = np.array([1, 4, -3, 8])
x = prelu(x)
print(x)
print(prelu_grad(x))

[ 1.    4.   -0.03  8.  ]
[1.   1.   0.01 1.  ]


# Erelu

In [17]:
def erelu(x, alpha = 0.01):
    return np.where(x > 0, x, alpha * np.exp(x) - 1)
def erelu_grad(x, alpha = 0.01):
    fx = erelu(x)
    return np.where(x > 0, 1, fx + alpha)

In [18]:
x = np.array([1, 4, -3, 8])
x = erelu(x)
print(x)
print(erelu_grad(x))

[ 1.          4.         -0.99950213  8.        ]
[ 1.          1.         -0.98631937  1.        ]


In [20]:
np.random.seed(1)
X = np.random.randn(2, 3)
y = (np.random.randn(1, 3) > 0)
print(X)
print(y)

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]]
[[ True False  True]]
