In [1]:
##Logistic Regression
import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import seaborn as sns
import statsmodels.formula.api as smf

In [2]:
df=pd.read_csv('chd.csv',header=0).dropna()

In [3]:
df.head(1)
df.isna().sum()

Age    0
CHD    0
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     100 non-null    int64
 1   CHD     100 non-null    int64
dtypes: int64(2)
memory usage: 1.7 KB


In [14]:
fit=smf.logit('CHD~Age',df).fit()
fit.summary()

Optimization terminated successfully.
         Current function value: 0.536765
         Iterations 6


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                    CHD   No. Observations:                  100
Model:                          Logit   Df Residuals:                       98
Method:                           MLE   Df Model:                            1
Date:                Tue, 26 Mar 2024   Pseudo R-squ.:                  0.2145
Time:                        21:10:41   Log-Likelihood:                -53.677
converged:                       True   LL-Null:                       -68.331
Covariance Type:            nonrobust   LLR p-value:                 6.168e-08
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -5.3095      1.134     -4.683      0.000      -7.531      -3.088
Age            0.1109      0.024      4.610      0.000       0.064       0.158
==============================================================================
"""

In [27]:
lr=LogisticRegression()
X=np.array(df['Age']).reshape(100,1)   ##df.iloc,df['spl','s
Y=df['CHD']
lr_fit=lr.fit(X,Y)
print(lr_fit.coef_)
print(lr_fit.intercept_)

[[0.1108579]]
[-5.30653265]


In [30]:
Y_pred=fit.predict(df['Age'])
Y_pred=np.round(Y_pred)

In [32]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y, Y_pred)

array([[45, 12],
       [14, 29]], dtype=int64)

In [34]:
from sklearn.metrics import accuracy_score
accuracy_score(Y, Y_pred)

0.74

In [42]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
model = LogisticRegression()
K=5
kfold = KFold(K,random_state=0,shuffle=True)
mse_cv = cross_val_score(model,X,Y,cv=kfold,scoring='accuracy')
mse_cv

array([0.8 , 0.65, 0.7 , 0.85, 0.65])

In [5]:
fitl=smf.logit('CHD~Age',df).fit()
fitl.summary().tables[1]

Optimization terminated successfully.
         Current function value: 0.536765
         Iterations 6


,coef,std err,z,P>|z|,[0.025,0.975]
Intercept,-5.3095,1.134,-4.683,0.000,-7.531,-3.088
Age,0.1109,0.024,4.610,0.000,0.064,0.158


In [9]:
y_prd=fitl.predict(df['Age'])
y_prd=np.round(y_prd)
y_prd

0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
     ... 
95    1.0
96    1.0
97    1.0
98    1.0
99    1.0
Length: 100, dtype: float64

In [10]:
from sklearn.metrics import confusion_matrix

In [12]:
confusion_matrix(df['CHD'],y_prd)

array([[45, 12],
       [14, 29]], dtype=int64)

In [13]:
df['CHD'].value_counts()

CHD
0    57
1    43
Name: count, dtype: int64

In [14]:
12+14

26

In [15]:
1-(26/100)

0.74

In [16]:
from sklearn.metrics import accuracy_score

In [17]:
accuracy_score(df['CHD'],y_prd)

0.74

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X=df['Age']
Y=df['CHD']
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,Y,test_size=0.20,random_state=123)

In [23]:
df_train=pd.concat([Xtrain,Ytrain],axis=1)
df_train.head(2)

,Age,CHD
35,39,0
88,59,1


In [24]:
fit_train=smf.logit('CHD~Age',df_train).fit()
fit_train.summary().tables[1]

Optimization terminated successfully.
         Current function value: 0.512058
         Iterations 6


,coef,std err,z,P>|z|,[0.025,0.975]
Intercept,-5.8703,1.335,-4.398,0.000,-8.487,-3.254
Age,0.1186,0.028,4.268,0.000,0.064,0.173


In [32]:
Y_prd_train=fit_train.predict(df_train['Age'])
Y_prd_train=np.round(Y_prd_train)
print(confusion_matrix(df_train['CHD'],Y_prd_train))
print(accuracy_score(df_train['CHD'],Y_prd_train))

[[40  8]
 [12 20]]
0.75


In [31]:
Y_prd_test=fit_train.predict(Xtest)
Y_prd_test=np.round(Y_prd_test)
print(confusion_matrix(Ytest,Y_prd_test))
print(accuracy_score(Ytest,Y_prd_test))

[[8 1]
 [5 6]]
0.7


In [33]:
model = LogisticRegression()

In [37]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
model = LogisticRegression()
X=df['Age'].values.reshape(-1,1)
Y=df['CHD']
K=5
kfold = KFold(K,random_state=0,shuffle=True)
mse_cv = cross_val_score(model,X,Y,cv=kfold,scoring='accuracy')
mse_cv

array([0.8 , 0.65, 0.7 , 0.85, 0.65])

In [1]:
from sklearn.linear_model import LogisticRegression

In [ ]:
X=df[['sl','pl','sw','pw']]
y=df['type']
logit=LogisticRegression()
logit.fit(X,Y)
logit.coef_
logit.intercept_
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred=logit.predict(X)
print(confusion_matrix(y,y_pred))
print(accuracy_score(y,y_pred))